# fly.toml file generated for protohackers-prime on 2023-01-16T21:09:42-05:00

app = "protohackers-prime"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    port = 9000
