# fly.toml file generated for aged-dust-7628 on 2023-01-29T16:40:32-05:00

app = "aged-dust-7628"
kill_signal = "SIGINT"
kill_timeout = 5

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 200
    soft_limit = 150

  [[services.ports]]
    port = 9000
